CREATE DATABASE OSK
GO

USE OSK
GO
/*
drop table UCZENIE
drop table kurs
drop table kursant
drop table instruktor */

CREATE TABLE KURS
(
    ID_kurs INTEGER IDENTITY(1,1) PRIMARY KEY,
    Nazwa VARCHAR(100) NOT NULL,
    Kategoria VARCHAR(1) CHECK (Kategoria in ('A', 'B', 'C')) NOT NULL,
    Typ VARCHAR(15) CHECK (Typ in ('PODSTAWOWY', 'UZUPELNIAJACY')) NOT NULL,
    Godziny INTEGER NOT NULL
)
GO

CREATE TABLE KURSANT
(
    PESEL VARCHAR(11) PRIMARY KEY,
    Imie VARCHAR(15) NOT NULL,
    Nazwisko VARCHAR(30) NOT NULL,
    Adres VARCHAR(100) NOT NULL,
    NumTel VARCHAR(12) NOT NULL
)
GO

CREATE TABLE INSTRUKTOR
(
    ID_instr INTEGER PRIMARY KEY,
    Imie VARCHAR(15) NOT NULL,
    Nazwisko VARCHAR(30) NOT NULL,
    Uprawnienia VARCHAR(1) CHECK (Uprawnienia in ('T', 'P')) NOT NULL,
    Kategorie VARCHAR(15) NOT NULL,
    DataZatrudnienia DATE NOT NULL,
    DataUprawnien DATE NOT NULL,
    DataUrodzenia DATE NOT NULL,
	NumTel VARCHAR(12) NOT NULL,
    Adres VARCHAR(100) NOT NULL
)
GO

CREATE TABLE UCZENIE
(
    ID_kurs INTEGER REFERENCES KURS NOT NULL,
    PESEL VARCHAR(11) REFERENCES KURSANT NOT NULL,
    ID_instr_T INTEGER REFERENCES INSTRUKTOR NULL,
    ID_instr_P INTEGER REFERENCES INSTRUKTOR NULL,
	DataRozpoczecia DATE NOT NULL,
    PodejsciaTeoria INTEGER NULL,
    PodejsciaPraktyka INTEGER NULL
    PRIMARY KEY (ID_kurs, PESEL, DataRozpoczecia)
)
GO